name: couldai_user_app
description: "Aplicativo educativo de jogos de contabilidade financeira para estudantes, empreendedores e iniciantes."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.9.1
  shared_preferences: ^2.2.3  # Para salvar progresso localmente
  provider: ^6.1.2  # Para gerenciamento de estado

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/  # Para ícones e imagens dos jogos
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700